[package]
name = "actix-elasticsearch"
version = "0.1.0"
authors = ["nashgao <nashgao1992@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
